refactor: re-introduce fuel-streams-publisher
FuelLabs/data-systems pull request #102
Opened 2024-07-26 11:56 UTC by Jurshsmith

This change renames fuel-core-nats to fuel-streams-publisher to accurately depict what the binary (runtime) would be used for.

References: https://github.com/FuelLabs/data-systems/issues/98

2024-07-30 16:57 UTC, cue8it requested changes
Please bump Chart version (I suggest 0.3.0 but up to you guys to decide).

2024-07-31 14:10 UTC, pedronauck approved these changes

2024-07-31 14:17 UTC, 0xterminator approved these changes
Nice work!

2024-07-31 16:27 UTC, cue8it approved these changes

2024-07-31 16:32 UTC, merged