Automate running fuel-core-nats locally
FuelLabs/data-systems pull request #20
Opened 2024-06-12 12:02 UTC by Jurshsmith

2024-06-12 17:45 UTC, pedronauck requested changes

2024-06-12 17:48 UTC, pedronauck commented
@Jurshsmith, what do you think about including the local `fuel-core-nats` component in Docker Compose, configured with the correct environment variables? This way, we can provide a Docker Compose example with all the necessary tools pre-configured as I mentioned in our sync.

2024-06-13 11:35 UTC, Jurshsmith commented
@pedronauck Thanks for bringing that up again. The plan is to first prepare the Docker image for fuel-core-nats. Once that's ready, we'll create a docker-compose template like you've described. I don't think we will need this for development though, since `fuel-core-nats` is new and unstable.

2024-06-17 17:47 UTC, Jurshsmith commented on Makefile
> +start.fuel-core-nats:
Ended up with `start` to allow the use of `stop` DSL in the script for stopping `docker-compose` services

2024-06-19 18:41 UTC, pedronauck approved these changes

2024-06-20 19:20 UTC, pedronauck approved these changes

2024-06-20 19:20 UTC, merged