refactor(publisher): Refactor examples
FuelLabs/data-systems pull request #264
Opened 2024-10-15 17:38 UTC by lostman

This PR refactors the examples:

1. Removed client and publisher examples, as this is something other than what the users would do.
2. Renamed streams to multiple-streams
3. Examples now work with `cargo run --example transactions/receipts/multiple-streams`

2024-10-15 18:02 UTC, pedronauck requested changes

2024-10-15 18:02 UTC, pedronauck commented on examples/Cargo.toml
> +name = "fuel-data-systems-examples"
```suggestion
name = "fuel-streams-examples"
```

2024-10-15 18:02 UTC, pedronauck commented on examples/receipts.rs
> +async fn stream_contract_events(
please, add everything in a `main` function instead of call this other function, as much simple as possible

2024-10-17 19:35 UTC, Jurshsmith submitted a review, later dismissed

2024-10-18 13:41 UTC, 0xterminator commented
@lostman I dont understand why we need separate examples for receipts e.g. provided they are covered by the multiple-streams. My original idea was to put everything in the streams so that the user could just check what we offer and use it. I fyou do that, you would also have to create N other examples for logs, utxos etc. I dont agree we dont need the client ones just because you as a user would have to build a client first ot be able to use the streams. We just demonstrate the different abilities of building a client. I think you might want to keep the publisher too as this would simply show how the sdk could also be used in  a different context in case the user would want to publish messages to his own context e.g. I find it useful as many users would want to do something else with the fuel messages they read.

2024-10-18 18:38 UTC, pedronauck commented
> @lostman I dont understand why we need separate examples for receipts e.g. provided they are covered by the multiple-streams. My original idea was to put everything in the streams so that the user could just check what we offer and use it. I fyou do that, you would also have to create N other examples for logs, utxos etc. I dont agree we dont need the client ones just because you as a user would have to build a client first ot be able to use the streams. We just demonstrate the different abilities of building a client. I think you might want to keep the publisher too as this would simply show how the sdk could also be used in a different context in case the user would want to publish messages to his own context e.g. I find it useful as many users would want to do something else with the fuel messages they read.

@0xterminator, we discussed this in a meeting that you couldn't participate in. This examples folder is something very focused on the user that consumes the SDK; it's a place they will look to get an overview of how the code works and figure out how to use the project. They need to be simple, and the user needs to quickly find what they want; adding everything inside a single `stream.rs` file makes it harder to find out. I showed up [this](https://github.com/nats-io/nats.rs/tree/main/async-nats/examples) and [this](https://github.com/FuelLabs/fuels-rs/tree/master/examples) examples folder as a reference.

But I agree with you. Since @lostman separated transactions and receipts, he should, of course, add the rest.

2024-10-18 21:28 UTC, pedronauck requested changes
Can you add the rest of the modules as example?

2024-10-21 11:43 UTC, lostman commented
> Can you add the rest of the modules as example?

Can you be more specific? What do you mean by "rest of the modules"?

2024-10-21 12:25 UTC, lostman commented
Added more examples:

```
[[example]]
name = "blocks"
path = "blocks.rs"

[[example]]
name = "transactions"
path = "transactions.rs"

[[example]]
name = "receipts"
path = "receipts.rs"

[[example]]
name = "inputs"
path = "inputs.rs"

[[example]]
name = "outputs"
path = "outputs.rs"

[[example]]
name = "utxos"
path = "utxos.rs"

[[example]]
name = "logs"
path = "logs.rs"
```

They are all very, very barebones. Simply subscribe to the default stream. Is that what you have in mind?

2024-10-23 13:30 UTC, Jurshsmith approved these changes

2024-10-23 14:37 UTC, merged