fix(core): Added retry in case of store creation timeout
FuelLabs/data-systems pull request #283
Opened 2024-10-24 12:02 UTC by 0xterminator

Added retry strategy for store creation in case of a timeout  (currently happening on the cluster).

2024-10-24 17:28 UTC, pedronauck submitted a review, later dismissed

2024-10-24 19:06 UTC, Jurshsmith requested changes
Let's delegate retries to Kubernetes for now. The store creation is failing due to NATS' previous OOM error. The cluster is in a state where it can't handle incoming traffic because it is migrating all the old data from the 400 GiB memory to the new 800 GiB

2024-10-25 02:29 UTC, pedronauck commented
> Let's delegate retries to Kubernetes for now. The store creation is failing due to NATS' previous OOM error. The cluster is in a state where it can't handle incoming traffic because it is migrating all the old data from the 400 GiB memory to the new 800 GiB

I agree with AJ on that, I don't issues when creating stores to add a retry mechanism right now

2024-10-25 06:25 UTC, 0xterminator commented
ok, closing it for now.

2024-10-25 06:25 UTC, closed without merging